title: Liam Arbuckle
email: liam.chairman@allianceofdroids.org.au
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/adam-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Liam Arbuckle # add your name
author-pic: runners.PNG
about-author: My name is Liam Arbuckle. I'm a 17 year old games developer and I'm going into university to study software engineering.

# Contact links
email: liam.chairman@allianceofdroids.org.au
phone: +61 466 225 878
website: allianceofdroids.org.au
linkedin: # Add your Linkedin handle
github: IrisDroidology # Add your Github handle
twitter: '@OpusTheRobot' # Add your Twitter handle
facebook: droidology
instagram: droidology
pinterest: droidology

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: acordrobotics # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
